#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::too_many_lines // long but linear integration setup; splitting hurts readability
)]

//! Phase-2 capstone: a *script-bearing skill* runs end to end through the
//! Runtime, exercising the whole skill-support stack in one turn.
//!
//! A skill bundle lives **outside** the session workspace. The model:
//!   1. `read_file`s a bundled script by its absolute skill-root path — proving
//!      the read-only skill-root scope reaches the bundle (ADR-0032), wired from
//!      the `SkillProvider` into `ExecCtx.skill_roots`.
//!   2. runs that bundled script via `bash` with no explicit `cwd` — proving the
//!      command runs in the **workspace root** (ADR-0031 §5 exec-cwd
//!      unification) and that bundled scripts are runnable (ADR-0023 Position A).
//!
//! Assertions tie the chain together: the `read_file` result is the script's
//! source; the `bash` result carries the script's stdout; and the artifact the
//! script wrote landed **in the workspace** (not in the bundle, not in the
//! process cwd). This is the same chain a real model drives to generate a
//! `.pptx` with the `pptx` skill — here hermetic (`sh` + `echo`, no network).

use std::sync::Arc;
use std::time::Duration;

use cogito_core::runtime::{OpenMode, Runtime};
use cogito_jobs::{BashConfig, BashTool, LocalJobManager};
use cogito_mock_model::MockModelGateway;
use cogito_protocol::command::CommandExecutor;
use cogito_protocol::event::{ConversationEvent, EventPayload};
use cogito_protocol::gateway::{ModelEvent, ModelGateway, StopReason, Usage};
use cogito_protocol::ids::SessionId;
use cogito_protocol::job::{JobManager, LocalJobSubmitter};
use cogito_protocol::skill::{SkillContent, SkillMetadata, SkillProvider, SkillSource};
use cogito_protocol::store::ConversationStore;
use cogito_protocol::strategy::HarnessStrategy;
use cogito_protocol::stream::StreamEvent;
use cogito_protocol::tool::{ToolProvider, ToolResult};
use cogito_sandbox::{DirectConfig, DirectExecutor};
use cogito_store::JsonlStore;
use cogito_tools::{
    BuiltinToolProvider, CompositeToolProvider, LocalWorkspace, NamingPolicy, ReadFile,
};
use futures::StreamExt as _;

/// A skill whose bundle lives at `root`; `skill_roots()` exposes it so the
/// Runtime injects it into `ExecCtx.skill_roots` (the #49 wiring under test).
struct BundledSkillProvider {
    root: std::path::PathBuf,
}

impl SkillProvider for BundledSkillProvider {
    fn list(&self) -> Vec<SkillMetadata> {
        vec![SkillMetadata {
            name: "deckgen".into(),
            description: "demo skill with a bundled generator script".into(),
            source: SkillSource::User,
            disable_model_invocation: false,
            user_invocable: true,
            version: None,
        }]
    }

    fn get(&self, name: &str) -> Option<SkillContent> {
        (name == "deckgen").then(|| SkillContent {
            name: "deckgen".into(),
            source: SkillSource::User,
            body: "## deckgen".into(),
            root: Some(self.root.clone()),
        })
    }

    fn is_registered(&self, name: &str) -> bool {
        name == "deckgen"
    }

    fn skill_roots(&self) -> Vec<std::path::PathBuf> {
        vec![self.root.clone()]
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn script_bearing_skill_reads_then_runs_bundled_script_into_workspace()
-> Result<(), Box<dyn std::error::Error>> {
    // Skill bundle on disk, OUTSIDE any workspace. Its script writes an artifact
    // to the current working directory and prints a marker to stdout.
    let skill = tempfile::tempdir()?;
    std::fs::create_dir(skill.path().join("scripts"))?;
    let script_src = "echo 'deck generated by skill' > deck.txt\necho GEN_OK\n";
    std::fs::write(skill.path().join("scripts").join("gen.sh"), script_src)?;
    let bundled = skill.path().join("scripts").join("gen.sh");

    // Session workspace: a *different* tempdir. The artifact must land here.
    let ws = tempfile::tempdir()?;

    let store_dir = tempfile::tempdir()?;
    let store = Arc::new(JsonlStore::new(store_dir.path().to_path_buf()));

    let job_mgr = LocalJobManager::new();
    let executor: Arc<dyn CommandExecutor> = Arc::new(DirectExecutor::new(DirectConfig::default()));
    let bash: Arc<dyn ToolProvider> = Arc::new(BashTool::new(
        executor,
        Arc::clone(&job_mgr) as Arc<dyn LocalJobSubmitter>,
        BashConfig::default(),
    ));
    let builtin: Arc<dyn ToolProvider> = Arc::new(
        BuiltinToolProvider::builder()
            .with_tool(Arc::new(ReadFile))
            .build(),
    );
    let tools: Arc<dyn ToolProvider> = Arc::new(CompositeToolProvider::new(
        vec![builtin, bash],
        NamingPolicy::Strict,
    )?);

    let provider: Arc<dyn SkillProvider> = Arc::new(BundledSkillProvider {
        root: skill.path().to_path_buf(),
    });

    let mock = Arc::new(MockModelGateway::new());
    // Turn 1: read the bundled script by its absolute skill-root path.
    mock.push_reply(vec![
        ModelEvent::ToolUseStarted {
            block_index: 0,
            call_id: "c1".into(),
            tool_name: "read_file".into(),
        },
        ModelEvent::ToolUseCompleted {
            block_index: 0,
            call_id: "c1".into(),
            tool_name: "read_file".into(),
            args: serde_json::json!({ "path": bundled.to_str().unwrap() }),
        },
        ModelEvent::MessageCompleted {
            stop_reason: StopReason::ToolUse,
            usage: Usage {
                input_tokens: 1,
                output_tokens: 1,
            },
        },
    ]);
    // Turn 2: run it via bash with no `cwd` -> defaults to the workspace root.
    let run_cmd = format!("sh '{}'", bundled.to_str().unwrap());
    mock.push_reply(vec![
        ModelEvent::ToolUseStarted {
            block_index: 0,
            call_id: "c2".into(),
            tool_name: "bash".into(),
        },
        ModelEvent::ToolUseCompleted {
            block_index: 0,
            call_id: "c2".into(),
            tool_name: "bash".into(),
            args: serde_json::json!({ "command": run_cmd }),
        },
        ModelEvent::MessageCompleted {
            stop_reason: StopReason::ToolUse,
            usage: Usage {
                input_tokens: 1,
                output_tokens: 1,
            },
        },
    ]);
    // Turn 3: final text, end the turn.
    mock.push_reply(vec![
        ModelEvent::TextDelta {
            block_index: 0,
            chunk: "done".into(),
        },
        ModelEvent::TextBlockCompleted {
            block_index: 0,
            text: "done".into(),
        },
        ModelEvent::MessageCompleted {
            stop_reason: StopReason::EndTurn,
            usage: Usage::default(),
        },
    ]);

    let runtime = Runtime::builder()
        .store(Arc::clone(&store) as Arc<dyn ConversationStore>)
        .model(Arc::clone(&mock) as Arc<dyn ModelGateway>)
        .tools(tools)
        .skills(provider)
        .workspace(Arc::new(LocalWorkspace::new(ws.path())))
        .job_manager(Arc::clone(&job_mgr) as Arc<dyn JobManager>)
        .strategy(HarnessStrategy::default_with_model("mock"))
        .build()?;

    let session_id = SessionId::new();
    let handle = runtime.open_session(session_id, OpenMode::New).await?;
    let mut events = handle.subscribe();
    handle
        .submit_user_text("generate the deck with the skill")
        .await?;

    let completed = tokio::time::timeout(Duration::from_secs(30), async {
        loop {
            match events.recv().await {
                Ok(StreamEvent::TurnCompleted { .. }) => return true,
                Ok(StreamEvent::TurnFailed { .. }) | Err(_) => return false,
                Ok(_) => {}
            }
        }
    })
    .await
    .unwrap_or(false);
    assert!(completed, "turn did not complete within 30s");
    handle.shutdown(Duration::from_secs(10)).await?;

    let log: Vec<ConversationEvent> = {
        let mut s = store.replay(session_id, 0);
        let mut out = Vec::new();
        while let Some(evt) = s.next().await {
            out.push(evt?);
        }
        out
    };
    let result_for = |cid: &str| -> ToolResult {
        log.iter()
            .find_map(|e| match &e.payload {
                EventPayload::ToolResultRecorded { call_id, result } if call_id == cid => {
                    Some(result.clone())
                }
                _ => None,
            })
            .unwrap_or_else(|| panic!("ToolResultRecorded for {cid} missing"))
    };

    // 1. read_file reached the bundled script via the skill-root scope (ADR-0032).
    match result_for("c1") {
        ToolResult::Output(blocks) => {
            assert_eq!(
                blocks[0].as_str().expect("text block"),
                script_src,
                "read_file must return the bundled script source"
            );
        }
        other => panic!("read_file: expected Output, got {other:?}"),
    }

    // 2. bash ran the bundled script and captured its stdout marker.
    match result_for("c2") {
        ToolResult::Output(blocks) => {
            let stdout = blocks[0]
                .get("stdout")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("");
            assert!(
                stdout.contains("GEN_OK"),
                "bash stdout missing marker: {stdout:?}"
            );
        }
        other => panic!("bash: expected Output, got {other:?}"),
    }

    // 3. The artifact landed in the WORKSPACE (no `cwd` -> workspace root, ADR-0031
    //    §5), not in the bundle and not in the process cwd.
    let artifact = ws.path().join("deck.txt");
    assert!(
        artifact.is_file(),
        "script artifact must be created in the workspace root"
    );
    assert_eq!(
        std::fs::read_to_string(&artifact)?.trim(),
        "deck generated by skill"
    );
    assert!(
        !skill.path().join("scripts").join("deck.txt").exists(),
        "artifact must NOT be written into the skill bundle"
    );

    Ok(())
}
